# Generated by Django 5.1.1 on 2024-09-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=15)),
                ('received_date', models.DateField()),
                ('inventory_received', models.TextField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('reported_issues', models.TextField()),
                ('client_notes', models.TextField()),
                ('assigned_technician', models.CharField(max_length=255)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
